# Generated by Django 5.0.1 on 2024-04-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rfid', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('nombrePassage', models.IntegerField()),
                ('estAutorise', models.BooleanField()),
            ],
        ),
    ]
